"""Synthetic clinical trial shipment generator, with injected cold-chain breaches.

Shipments travel from a small set of regional depots (not clinical sites
themselves -- this matches how clinical trial drug supply actually moves:
central/regional depot -> site) to one of the sites generated by
`pipeline.generators.sites`.
"""

from __future__ import annotations

import logging
import random
from datetime import UTC, datetime, timedelta

logger = logging.getLogger(__name__)

CARRIERS = [
    "World Courier",
    "Marken",
    "FedEx Custom Critical",
    "UPS Healthcare",
    "DHL Medical Express",
    "Cryoport Systems",
]

DEPOTS = [
    "DEPOT-US-EAST",
    "DEPOT-US-WEST",
    "DEPOT-EU-CENTRAL",
    "DEPOT-EU-WEST",
    "DEPOT-APAC",
    "DEPOT-LATAM",
]

# (profile name, (min_c, max_c), selection weight)
TEMP_PROFILES: list[tuple[str, tuple[float, float], float]] = [
    ("refrigerated", (2.0, 8.0), 0.6),
    ("controlled_room_temperature", (15.0, 25.0), 0.3),
    ("frozen", (-25.0, -15.0), 0.1),
]

DEFAULT_COLD_CHAIN_ANOMALY_RATE = 0.08
READING_INTERVAL_MINUTES = 45


def _weighted_choice(rng: random.Random, options: list[tuple[str, tuple[float, float], float]]):
    names, ranges, weights = zip(*options, strict=True)
    idx = rng.choices(range(len(options)), weights=weights, k=1)[0]
    return names[idx], ranges[idx]


def _generate_temperature_log(
    rng: random.Random,
    start: datetime,
    end: datetime,
    temp_range: tuple[float, float],
    inject_breach: bool,
    breach_minutes_threshold: int,
) -> list[dict]:
    """Generate readings every `READING_INTERVAL_MINUTES` across transit.

    If `inject_breach`, a contiguous span of readings longer than
    `breach_minutes_threshold` is deliberately pushed outside `temp_range` so
    `pipeline.anomaly.cold_chain` has a real signal to detect.
    """
    lo, hi = temp_range
    midpoint = (lo + hi) / 2
    total_minutes = max(int((end - start).total_seconds() // 60), READING_INTERVAL_MINUTES)
    n_readings = max(total_minutes // READING_INTERVAL_MINUTES, 2)

    breach_start_idx: int | None = None
    breach_len: int | None = None
    if inject_breach:
        breach_reading_span = max(breach_minutes_threshold // READING_INTERVAL_MINUTES + 1, 2)
        breach_len = breach_reading_span + rng.randint(0, 3)
        breach_len = min(breach_len, max(n_readings - 1, 1))
        breach_start_idx = rng.randint(0, max(n_readings - breach_len - 1, 0))

    readings = []
    current_temp = midpoint
    for i in range(n_readings):
        timestamp = start + timedelta(minutes=i * READING_INTERVAL_MINUTES)
        in_breach = breach_start_idx is not None and breach_start_idx <= i < (
            breach_start_idx + breach_len
        )
        if in_breach:
            direction = 1 if rng.random() < 0.5 else -1
            current_temp = hi + rng.uniform(3, 10) if direction > 0 else lo - rng.uniform(3, 10)
        else:
            # Small random walk within the valid range, gently pulled back
            # toward the midpoint so it doesn't drift out of range by chance.
            current_temp += rng.uniform(-0.6, 0.6) + (midpoint - current_temp) * 0.1
            current_temp = min(max(current_temp, lo), hi)
        readings.append({"timestamp": timestamp.isoformat(), "temp_c": round(current_temp, 2)})

    return readings


def generate_shipments(
    sites: list[dict],
    n_shipments: int = 50_000,
    seed: int = 42,
    cold_chain_anomaly_rate: float = DEFAULT_COLD_CHAIN_ANOMALY_RATE,
    breach_minutes_threshold: int = 30,
    as_of: datetime | None = None,
    lookback_days: int = 180,
) -> list[dict]:
    """Generate synthetic clinical trial shipments.

    Args:
        sites: Output of `pipeline.generators.sites.generate_sites` --
            shipments are addressed to a `(trial_id, site_id)` drawn from it.
        n_shipments: Total number of shipments to generate.
        seed: RNG seed; the same seed always produces the same shipments.
        cold_chain_anomaly_rate: Fraction of shipments with a deliberately
            injected sustained temperature excursion.
        breach_minutes_threshold: Minimum duration (in minutes) an injected
            breach is guaranteed to last -- matches
            `pipeline.anomaly.cold_chain`'s detection threshold by default.
        as_of: "Today" for the purposes of the shipment lookback window.
        lookback_days: Shipments are spread across the `lookback_days` days
            before `as_of`.

    Returns:
        One dict per shipment with keys: shipment_id, trial_id, origin_site,
        destination_site, carrier, ship_timestamp, expected_arrival,
        actual_arrival, temperature_log, required_temp_range,
        _ground_truth_cold_chain_breach.
    """
    if not sites:
        raise ValueError("generate_shipments requires at least one site")

    rng = random.Random(seed)
    as_of = as_of or datetime.now(UTC)

    shipments: list[dict] = []
    for i in range(1, n_shipments + 1):
        shipment_id = f"SHP-{i:06d}"
        site = rng.choice(sites)
        trial_id = site["trial_id"]
        destination_site = site["site_id"]
        origin_site = rng.choice(DEPOTS)
        carrier = rng.choice(CARRIERS)

        ship_timestamp = as_of - timedelta(
            days=rng.uniform(0, lookback_days), hours=rng.uniform(0, 23)
        )
        transit_hours = rng.uniform(24, 96)
        expected_arrival = ship_timestamp + timedelta(hours=transit_hours)
        delay_hours = max(0.0, rng.gauss(2, 6))
        actual_arrival = expected_arrival + timedelta(hours=delay_hours)

        _, temp_range = _weighted_choice(rng, TEMP_PROFILES)
        inject_breach = rng.random() < cold_chain_anomaly_rate
        temperature_log = _generate_temperature_log(
            rng, ship_timestamp, actual_arrival, temp_range, inject_breach, breach_minutes_threshold
        )

        shipments.append(
            {
                "shipment_id": shipment_id,
                "trial_id": trial_id,
                "origin_site": origin_site,
                "destination_site": destination_site,
                "carrier": carrier,
                "ship_timestamp": ship_timestamp.isoformat(),
                "expected_arrival": expected_arrival.isoformat(),
                "actual_arrival": actual_arrival.isoformat(),
                "temperature_log": temperature_log,
                "required_temp_range": [temp_range[0], temp_range[1]],
                "_ground_truth_cold_chain_breach": inject_breach,
            }
        )

    logger.info(
        "Generated %d shipments (%d with an injected cold-chain breach)",
        len(shipments),
        sum(1 for s in shipments if s["_ground_truth_cold_chain_breach"]),
    )
    return shipments
